global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: greenharvest-backend
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          service: backend
  - job_name: celery-worker
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5555']
        labels:
          service: celery_flower



